// Mock data for development - Replace with API calls when backend is ready

import type { User, Ticket, RewardStatus, Activity, Event } from './types'

export const currentUser: User = {
  id: 'user_001',
  walletAddress: '8xkJ...B9Dp',
  phone: '+52 55 1234 5678',
  phoneVerified: true,
  role: 'attendee',
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-10-24T14:30:00Z',
}

export const currentTickets: Ticket[] = [
  {
    id: 'ticket_001',
    eventId: 'event_001',
    eventName: 'CYBERPUNK\nNIGHTS',
    eventDate: '2024-10-24',
    venue: 'NEON DISTRICT HUB',
    status: 'active',
    mintAddress: '9xmK...C8Eq',
    ownerId: 'user_001',
    createdAt: '2024-09-15T10:00:00Z',
    checkInAt: null,
    tier: 'vip',
  },
  {
    id: 'ticket_002',
    eventId: 'event_002',
    eventName: 'SOLANA\nBREAKPOINT',
    eventDate: '2024-11-12',
    venue: 'CONVENTION CENTER',
    status: 'active',
    mintAddress: '7ynL...D7Fr',
    ownerId: 'user_001',
    createdAt: '2024-08-20T14:00:00Z',
    checkInAt: null,
    tier: 'platinum',
  },
  {
    id: 'ticket_003',
    eventId: 'event_003',
    eventName: 'SUMMER\nROOFTOP',
    eventDate: '2024-08-15',
    venue: 'SKY GARDEN',
    status: 'used',
    mintAddress: '5zoM...E6Gs',
    ownerId: 'user_001',
    createdAt: '2024-07-01T09:00:00Z',
    checkInAt: '2024-08-15T18:30:00Z',
    tier: 'general',
  },
]

export const rewardStatus: RewardStatus = {
  totalPoints: 2840,
  level: 4,
  levelName: 'Protocol Level 4',
  nextLevelPoints: 3500,
  progressPercent: 92,
  rewards: [
    {
      id: 'reward_001',
      name: 'OG Collector',
      description: 'Early adopter badge',
      icon: 'star',
      type: 'badge',
      status: 'active',
      unlockedAt: '2024-02-01T10:00:00Z',
    },
    {
      id: 'reward_002',
      name: 'Genesis Mint',
      description: 'Season 1 rare collectible',
      icon: 'clock',
      type: 'badge',
      status: 'active',
      unlockedAt: '2024-03-15T14:00:00Z',
    },
    {
      id: 'reward_003',
      name: 'Airdrop Multiplier',
      description: '1.2x multiplier active',
      icon: 'zap',
      type: 'multiplier',
      status: 'active',
      unlockedAt: '2024-06-01T09:00:00Z',
    },
    {
      id: 'reward_004',
      name: 'Ticket Confirmed',
      description: 'Unlock at level 5',
      icon: 'lock',
      type: 'perk',
      status: 'locked',
      requirements: 'Reach Protocol Level 5',
    },
  ],
}

export const activityHistory: Activity[] = [
  {
    id: 'activity_001',
    type: 'check_in',
    title: 'Check-in Verified',
    description: 'LOLLAPALOOZA 2024',
    timestamp: '2024-10-20T18:45:00Z',
    transactionHash: '3xAb...K9Lm',
    status: 'confirmed',
  },
  {
    id: 'activity_002',
    type: 'mint',
    title: 'Asset Minted',
    description: 'AFTERPARTY VIP PASS',
    timestamp: '2024-10-18T14:30:00Z',
    transactionHash: '7yNc...P2Qr',
    status: 'confirmed',
  },
  {
    id: 'activity_003',
    type: 'transfer',
    title: 'Ticket Transferred',
    description: 'TO 0X82...F91A',
    timestamp: '2024-10-15T11:20:00Z',
    transactionHash: '2zOd...R5Ts',
    status: 'confirmed',
  },
]

export const upcomingEvents: Event[] = [
  {
    id: 'event_004',
    name: 'Neon Genesis',
    description: 'Immersive digital art experience',
    date: '2024-12-01',
    venue: 'Digital Arts Center',
    organizerId: 'org_001',
    status: 'active',
    capacity: 500,
    ticketsSold: 342,
    imageUrl: '/events/neon-genesis.jpg',
    createdAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'event_005',
    name: 'Solana Summit',
    description: 'Annual blockchain conference',
    date: '2024-12-15',
    venue: 'Convention Center',
    organizerId: 'org_002',
    status: 'active',
    capacity: 2000,
    ticketsSold: 1456,
    imageUrl: '/events/solana-summit.jpg',
    createdAt: '2024-08-15T14:00:00Z',
  },
  {
    id: 'event_006',
    name: 'Voxel Art Expo',
    description: '3D art and NFT showcase',
    date: '2025-01-10',
    venue: 'Modern Art Museum',
    organizerId: 'org_003',
    status: 'active',
    capacity: 300,
    ticketsSold: 89,
    imageUrl: '/events/voxel-expo.jpg',
    createdAt: '2024-10-01T09:00:00Z',
  },
]
